library("RCassandra")
library("tm")
library("wordcloud")
c <- RC.connect("localhost")
RC.login(c,"foo","bar")
RC.use(c,"bdd")
df <- RC.read.table(c,"tweet",convert=FALSE)
sink('temp/texto.txt')
print(df,right=F)
sink()
texto<-Corpus(DirSource("temp/"))
texto<-tm_map(texto,stripWhitespace)
texto<-tm_map(texto,tolower)
texto<-tm_map(texto,removeWords,stopwords("english"))
texto<-tm_map(texto,removeWords,stopwords("spanish"))
texto<-tm_map(texto,stemDocument)
texto<-tm_map(texto,removeNumbers)
texto<-tm_map(texto,removePunctuation)
texto<-Corpus(VectorSource(texto))
wordcloud(texto,scale=c(5,0.5),max.words=100,random.order=FALSE,rot.per=0.35,use.r.layout=FALSE,colors=brewer.pal(8,"Dark2"))
RC.close(c)

